/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Ultimate Grocery Full App Flutter
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2024-present initappz.
*/
import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Profile": "Profile",
          "Edit": "Edit",
          "Sign In / Sign Up": "Sign In / Sign Up",
          "Orders": "Orders",
          "Favorites": "Favorites",
          "Your Address": "Your Address",
          "Wallet": "Wallet",
          "Refer & Earn": "Refer & Earn",
          "Change Password": "Change Password",
          "Languages": "Languages",
          "Chats": "Chats",
          "Contact Us": "Contact Us",
          "Faq & Help": "Faq & Help",
          "Privacy And Terms": "Privacy And Terms",
          "About": "About",
          "Logout": "Logout",
          "Session expired!": "Session expired!",
          "Please wait": "Please wait",
          "Address": "Address",
          "Add Address": "Add Address",
          "Cart": "Cart",
          "Your cart is empty": "Your cart is empty",
          "Your Cart": "Your Cart",
          "Order once placed cannot be cancelled and are non-refunable": "Order once placed cannot be cancelled and are non-refunable",
          " Items : ": " Items : ",
          "Checkout": "Checkout",
          " grams": " grams",
          " kg": " kg",
          " ltr": " ltr",
          " ml": " ml",
          " pcs": " pcs",
          "Choose variant": "Choose variant",
          "Categories": "Categories",
          "No Stores Found Near You!": "No Stores Found Near You!",
          "Delivery Options": "Delivery Options",
          "Delivery Address": "Delivery Address",
          "Payments": "Payments",
          "Note : Please visit all the stores listed on top": "Note : Please visit all the stores listed on top",
          "Next": "Next",
          "Payment": "Payment",
          "Delivery from": "Delivery from",
          "Stores": "Stores",
          "Delivery Time": "Delivery Time",
          "Select Time": "Select Time",
          "Coupon Applied": "Coupon Applied",
          "Apply Coupon code": "Apply Coupon code",
          "Remove": "Remove",
          "Balance": "Balance",
          "Available Balance ": "Available Balance ",
          "Item Total": "Item Total",
          "Taxes & Charges": "Taxes & Charges",
          "Discount": "Discount",
          "Wallet Balance": "Wallet Balance",
          "Delivery Charges": "Delivery Charges",
          "Grand Total": "Grand Total",
          "Select Payment Gateway": "Select Payment Gateway",
          "Complaints": "Complaints",
          "Issue With": "Issue With",
          "Select Store": "Select Store",
          "Select product": "Select product",
          "Select Driver": "Select Driver",
          "Select reason": "Select reason",
          "Title": "Title",
          "Brief of your issue": "Brief of your issue",
          "Comments": "Comments",
          "Write something on issue": "Write something on issue",
          "Upload Image": "Upload Image",
          "Submit": "Submit",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Message": "Message",
          "Best Deals": "Best Deals",
          " Items": " Items",
          "Popularity": "Popularity",
          "Price - Low to High": "Price - Low to High",
          "Price L-H": "Price L-H",
          "Price - Price L-H": "Price - Price L-H",
          "Price H-L": "Price H-L",
          "A - Z": "A - Z",
          "Z - A": "Z - A",
          "% Off - High to Low": "% Off - High to Low",
          "Filter ": "Filter ",
          "Add": "Add",
          "Edit Profile": "Edit Profile",
          "Choose From": "Choose From",
          "Gallery": "Gallery",
          "Camera": "Camera",
          "Cancel": "Cancel",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Email": "Email",
          "Mobile No": "Mobile No",
          "Save Profile": "Save Profile",
          "Connection Failed": "Connection Failed",
          "Could not connect to network,": "Could not connect to network,",
          "Please check and try again.": "Please check and try again.",
          "retry": "retry",
          "Your Favourite": "Your Favourite",
          "Verify your phone number": "Verify your phone number",
          "History": "History",
          "Opps, Please sign in or sign up first!": "Opps, Please sign in or sign up first!",
          "ORDER # ": "ORDER # ",
          "Search products": "Search products",
          "All Categories": "All Categories",
          "View All": "View All",
          "Exclusive Offers": "Exclusive Offers",
          "Top Picked": "Top Picked",
          "Products For You": "Products For You",
          "Top Stores": "Top Stores",
          "View": "View",
          "Message...": "Message...",
          "Fresh fruits and Vegetables": "Fresh fruits and Vegetables",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health",
          "Grocery to your door steps": "Grocery to your door steps",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.",
          "Best quality grocery": "Best quality grocery",
          "Best quality product with organic maintenance but with affordable price.": "Best quality product with organic maintenance but with affordable price.",
          "Fastest Delivery": "Fastest Delivery",
          "Free delivery service for highest cart value, without minimum payment.": "Free delivery service for highest cart value, without minimum payment.",
          "Skip": "Skip",
          "Previous": "Previous",
          "Get Started": "Get Started",
          "Enable Location": "Enable Location",
          "Set your location to start exploring grocery stores around you": "Set your location to start exploring grocery stores around you",
          "Use Current Location": "Use Current Location",
          "Enter Zipcode": "Enter Zipcode",
          "Set your zipcode to start exploring grocery stores around you": "Set your zipcode to start exploring grocery stores around you",
          "Select your city to start exploring grocery stores around you": "Select your city to start exploring grocery stores around you",
          "Select": "Select",
          "Welcome": "Welcome",
          "Please login to your acount": "Please login to your acount",
          "Password": "Password",
          "Forgot Password?": "Forgot Password?",
          "Sign In": "Sign In",
          "Don't have an account?": "Don't have an account?",
          " Sign Up": " Sign Up",
          "Phone Number": "Phone Number",
          "Send OTP": "Send OTP",
          "Location": "Location",
          "House / Flat No": "House / Flat No",
          "Landmark": "Landmark",
          "Pincode": "Pincode",
          "Save As": "Save As",
          "Home": "Home",
          "Work": "Work",
          "Other": "Other",
          "Add New Card": "Add New Card",
          "Card Holder Name": "Card Holder Name",
          "Card Number": "Card Number",
          "CVC": "CVC",
          "MM/YY": "MM/YY",
          "Add Card": "Add Card",
          "Offers": "Offers",
          "Rate Order": "Rate Order",
          "Cancel Order": "Cancel Order",
          "More Details": "More Details",
          "Amount to Pay": "Amount to Pay",
          "Deliver to": "Deliver to",
          "Basic Detail": "Basic Detail",
          "Order ID": "Order ID",
          "Payment Method": "Payment Method",
          "COD": "COD",
          "PAID": "PAID",
          "Delivery On": "Delivery On",
          "Order Tracking": "Order Tracking",
          "Stores Information": "Stores Information",
          "Drivers Information": "Drivers Information",
          "Descriptions": "Descriptions",
          "Heighlight": "Highlight",
          "Disclaimer": "Disclaimer",
          "Maybe You Likes": "Maybe You Likes",
          "Refer & Earns": "Refer & Earns",
          "Invite Friends": "Invite Friends",
          "Please register to your acount": "Please register to your acount",
          "Referral Code (Optional)": "Referral Code (Optional)",
          "By continuing, you agree to our ": "By continuing, you agree to our ",
          "Terms of Service": "Terms of Service",
          "Privacy Policy": "Privacy Policy",
          " and ": " and ",
          "Sign Up": "Sign Up",
          "Already have an account?": "Already have an account?",
          " Sign In": " Sign In",
          "Reset Password": "Reset Password",
          "Please enter your credentials": "Please enter your credentials",
          "New Password": "New Password",
          "Confirm Password": "Confirm Password",
          "Update Password": "Update Password",
          "No Internet Connection": "No Internet Connection",
          "Pay with Stripe": "Pay with Stripe",
          "Expiry ": "Expiry ",
          "Payment ": "Payment ",
          "Account": "Account",
          "Tracking Order": "Tracking Order",
          "Store Information": "Store Information",
          "Order Total": "Order Total",
          "Payment Method : ": "Payment Method : ",
          "Driver Information": "Driver Information",
          "All Transactions": "All Transactions",
          "At Home": "At Home",
          "Self Pickup": "Self Pickup",
          "Tomorrow - ": "Tomorrow - ",
          "Today - ": "Today - ",
          "Warning": "Warning",
          "You already have item's in cart with different grocery store": "You already have item's in cart with different grocery store",
          "Clear Cart": "Clear Cart",
          "Confirm": "Confirm",
          "Are you sure to delete this?": "Are you sure to delete this?",
          "Yes, Delete": "Yes, Delete",
          "Minimum order amount must be ": "Minimum order amount must be ",
          " or more": " or more",
          "coupon codes": "coupon codes",
          "Use coupon code ": "Use coupon code ",
          " - Valid until ": " - Valid until ",
          "Sorry minimum cart value must be ": "Sorry minimum cart value must be ",
          " or equal": " or equal",
          "Please Select Delivery Address": "Please Select Delivery Address",
          "Are you sure?": "Are you sure?",
          "Orders once placed cannot be cancelled and are non-refundable": "Orders once placed cannot be cancelled and are non-refundable",
          "Yes, Place Order": "Yes, Place Order",
          "Please Select Payment Method": "Please Select Payment Method",
          "Creating Order": "Creating Order",
          "Your Order Created Successfully": "Your Order Created Successfully",
          "You can view the order tracking info in the": "You can view the order tracking info in the",
          " Profile ": " Profile ",
          "section.": "section.",
          "Go to Home": "Go to Home",
          "Go to Order": "Go to Order",
          "The product arrived too late": "The product arrived too late",
          "The product did not match the description": "The product did not match the description",
          "The purchase was fraudulent": "The purchase was fraudulent",
          "The product was damaged or defective": "The product was damaged or defective",
          "The merchant shipped the wrong item": "The merchant shipped the wrong item",
          "Wrong Item Size or Wrong Product Shipped": "Wrong Item Size or Wrong Product Shipped",
          "Driver arrived too late": "Driver arrived too late",
          "Driver behavior": "Driver behavior",
          "Store Vendors behavior": "Store Vendors behavior",
          "Issue with Payment Amount": "Issue with Payment Amount",
          "Others": "Others",
          "Order": "Order",
          "Store": "Store",
          "Driver": "Driver",
          "Product": "Product",
          "Choose Issue With": "Choose Issue With",
          "Choose Store": "Choose Store",
          "Choose Driver": "Choose Driver",
          "Choose Reason": "Choose Reason",
          "Choose Product": "Choose Product",
          "All fields are required": "All fields are required",
          "Complaints registered": "Complaints registered",
          "Email is not valid": "Email is not valid",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon": "We have received your request, we will respond on your issue soon",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "Okay": "Okay",
          "Profile Updated": "Profile Updated",
          "A-Z": "A-Z",
          "Z-A": "Z-A",
          "% Off": "% Off",
          "Your account is suspended": "Your account is suspended",
          "Something went wrong while signup": "Something went wrong while signup",
          "Something went wrong": "Something went wrong",
          "Congratulations your friend have received the ": "Congratulations your friend have received the ",
          " on wallet": " on wallet",
          "Congratulations you have received the ": "Congratulations you have received the ",
          "Congratulations you & your friend have received the ": "Congratulations you & your friend have received the ",
          "Please add comments": "Please add comments",
          "Rating added": "Rating added",
          "Featching Location": "Featching Location",
          "Location services are disabled.": "Location services are disabled.",
          "Location permissions are denied": "Location permissions are denied",
          "Location permissions are permanently denied, we cannot request permissions.": "Location permissions are permanently denied, we cannot request permissions.",
          "Please enter your zipcode": "Please enter your zipcode",
          "Phone Number is required": "Phone Number is required",
          "Verification": "Verification",
          "We have sent verification code on": "We have sent verification code on",
          "Verify": "Verify",
          "Add New Address": "Add New Address",
          "Update Address": "Update Address",
          "could not determine your location": "could not determine your location",
          "Address saved": "Address saved",
          "Address Updated": "Address Updated",
          "Card Information Saved": "Card Information Saved",
          "Choose": "Choose",
          "Chat": "Chat",
          "Contact": "Contact",
          "Call": "Call",
          "Billing Information": "Billing Information",
          "Order Item Total": "Order Item Total",
          "Order Delivery Charge": "Order Delivery Charge",
          "Split Order Tax": "Split Order Tax",
          "Split Order Discount": "Split Order Discount",
          "Split Order Wallet Discount": "Split Order Wallet Discount",
          "Rate Driver": "Rate Driver",
          "to cancel this order?": "to cancel this order?",
          "Yes, Cancel Order": "Yes, Cancel Order",
          "Updating Order": "Updating Order",
          "Status Updated": "Status Updated",
          "Your friend": "Your friend",
          "has invited you to": "has invited you to",
          "Hey Buddy download": "Hey Buddy download",
          "from app store and use my code": "from app store and use my code",
          "while sign up we both will get": "while sign up we both will get",
          "wallet amount": "wallet amount",
          "Share with buddies": "Share with buddies",
          "Copied to clipboard": "Copied to clipboard",
          "Use this code for verification": "Use this code for verification",
          "Don't share this otp to anybody else": "Don't share this otp to anybody else",
          "Password mismatch": "Password mismatch",
          "Password Updated": "Password Updated",
          "Please select card": "Please select card",
          "Order Created": "Order Created",
          "Order cancelled by you": "Order cancelled by you",
          "Start Location": "Start Location",
          "End Location": "End Location",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "About Us": "About Us"
        },
        'hi_IN': {
          "Profile": "संपादन करना",
          "Edit": "संपादन करना",
          "Sign In / Sign Up": "प्रवेश या साइन अप",
          "Orders": "आदेश",
          "Favorites": "पसंदीदा",
          "Your Address": "तुम्हारा पता",
          "Wallet": "बटुआ",
          "Refer & Earn": "देखें और कमाएं",
          "Change Password": "पासवर्ड बदलें",
          "Languages": "बोली",
          "Chats": "चैट",
          "Contact Us": "संपर्क करें",
          "Faq & Help": "पूछे जाने वाले प्रश्न और सहायता",
          "Privacy And Terms": "गोपनीयता और शर्तें",
          "About": "के बारे में",
          "Logout": "लॉग आउट",
          "Session expired!": "सत्र समाप्त हुआ!",
          "Please wait": "कृपया प्रतीक्षा करें",
          "Address": "पता",
          "Add Address": "पता जोड़ें",
          "Cart": "कार्ट",
          "Your cart is empty": "आपकी गाड़ी खाली है",
          "Your Cart": "आपकी गाड़ी",
          "Order once placed cannot be cancelled and are non-refunable": "एक बार दिया गया आदेश रद्द नहीं किया जा सकता है और वापस नहीं किया जा सकता है",
          " Items : ": " सामान : ",
          "Checkout": "चेक आउट",
          " grams": " ग्राम",
          " kg": " किलोग्राम",
          " ltr": " लीटर",
          " ml": " एमएल",
          " pcs": " पीसीएस",
          "Choose variant": "प्रकार चुनें",
          "Categories": "श्रेणियाँ",
          "No Stores Found Near You!": "आपके आस-पास कोई स्टोर नहीं मिला!",
          "Delivery Options": "वितरण विकल्प",
          "Delivery Address": "डिलिवरी का पता",
          "Payments": "भुगतान",
          "Note : Please visit all the stores listed on top": "नोट: कृपया शीर्ष पर सूचीबद्ध सभी दुकानों पर जाएँ",
          "Next": "अगला",
          "Payment": "भुगतान",
          "Delivery from": "से वितरण",
          "Stores": "स्टोर",
          "Delivery Time": "डिलीवरी का समय",
          "Select Time": "समय चुनें",
          "Coupon Applied": "कूपन लागू",
          "Apply Coupon code": "कूपन कोड लागू करें",
          "Remove": "हटाना",
          "Balance": "संतुलन",
          "Available Balance ": "उपलब्ध शेष राशि ",
          "Item Total": "आइटम का कुल",
          "Taxes & Charges": "कर और शुल्क",
          "Discount": "छूट",
          "Wallet Balance": "वॉलेट बैलेंस",
          "Delivery Charges": "पहुंचाने का शुल्क",
          "Grand Total": "कुल योग",
          "Select Payment Gateway": "भुगतान गेटवे का चयन करें",
          "Complaints": "शिकायतों",
          "Issue With": "मुद्दे के साथ",
          "Select Store": "स्टोर चुनें",
          "Select product": "उत्पाद चुनें",
          "Select Driver": "ड्राइवर का चयन करें",
          "Select reason": "कारण चुनें",
          "Title": "शीर्षक",
          "Brief of your issue": "आपकी समस्या का संक्षिप्त विवरण",
          "Comments": "टिप्पणियाँ",
          "Write something on issue": "मुद्दे पर कुछ लिखें",
          "Upload Image": "तस्विर अपलोड करना",
          "Submit": "प्रस्तुत करना",
          "Full Name": "पूरा नाम",
          "Email Address": "ईमेल पता",
          "Message": "संदेश",
          "Best Deals": "सबसे अच्छे सौदे",
          " Items": " सामान",
          "Popularity": "लोकप्रियता",
          "Price - Low to High": "कीमतों का उतार - चढ़ाव",
          "Price L-H": "कीमत उच्च - निम्न",
          "Price - Price L-H": "मूल्य - उतार - चढ़ाव",
          "Price H-L": "कीमत का उतार - चढ़ाव",
          "A - Z": "ए - जेड",
          "Z - A": "जेड - ए",
          "% Off - High to Low": "% छूट - उच्च से निम्न",
          "Filter ": "फ़िल्टर ",
          "Add": "जोड़ें",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Choose From": "से चुनें",
          "Gallery": "गेलरी",
          "Camera": "कैमरा",
          "Cancel": "रद्द करना",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Email": "ईमेल",
          "Mobile No": "मोबाइल नहीं है",
          "Save Profile": "प्रोफ़ाइल बचा",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network,": "नेटवर्क से कनेक्ट नहीं हो सका,",
          "Please check and try again.": "कृपया जाँच करें और पुनः प्रयास करें।",
          "retry": "पुन: प्रयास करें",
          "Your Favourite": "आपका पसंदीदा",
          "Verify your phone number": "अपना फोन नम्बर सत्यापित करें",
          "History": "इतिहास",
          "Opps, Please sign in or sign up first!": "ओह, कृपया पहले साइन इन करें या साइन अप करें!",
          "ORDER # ": "गण # ",
          "Search products": "उत्पादों को खोजना",
          "All Categories": "सब वर्ग",
          "View All": "सभी को देखें",
          "Exclusive Offers": "विशेष ऑफर",
          "Top Picked": "शीर्ष चुना गया",
          "Products For You": "आपके लिए उत्पाद",
          "Top Stores": "शीर्ष स्टोर",
          "View": "राय",
          "Message...": "संदेश...",
          "Fresh fruits and Vegetables": "ताजे फल और सब्जियां",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "ताजे फल और सब्जियां स्वस्थ आहार का एक महत्वपूर्ण हिस्सा हैं। इनमें आवश्यक विटामिन, खनिज, फाइबर और अन्य पोषक तत्व होते हैं जो अच्छे स्वास्थ्य के लिए आवश्यक हैं",
          "Grocery to your door steps": "आपके दरवाजे तक किराना",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "हम धीरे-धीरे इस बारे में अधिक जागरूक हो रहे हैं कि हमारी व्यक्तिगत पसंद हमारे ग्रह को कैसे प्रभावित कर सकती है। और भोजन - हम इसका उपभोग कैसे करते हैं और हम इसके लिए कैसे खरीदारी करते हैं - यह सबसे महत्वपूर्ण तरीकों में से एक है जिससे हम फर्क कर सकते हैं।",
          "Best quality grocery": "उत्तम गुणवत्ता किराना",
          "Best quality product with organic maintenance but with affordable price.": "जैविक रखरखाव के साथ सर्वोत्तम गुणवत्ता वाला उत्पाद लेकिन सस्ती कीमत के साथ।",
          "Fastest Delivery": "सबसे तेज़ डिलीवरी",
          "Free delivery service for highest cart value, without minimum payment.": "न्यूनतम भुगतान के बिना उच्चतम कार्ट मूल्य के लिए निःशुल्क वितरण सेवा।",
          "Skip": "छोड़ें",
          "Previous": "पिछला",
          "Get Started": "शुरू हो जाओ",
          "Enable Location": "स्थान सक्षम करें",
          "Set your location to start exploring grocery stores around you": "अपने आस-पास किराना स्टोर की खोज शुरू करने के लिए अपना स्थान निर्धारित करें",
          "Use Current Location": "वर्तमान स्थान का उपयोग करें",
          "Enter Zipcode": "ज़िप कोड डालें",
          "Set your zipcode to start exploring grocery stores around you": "अपने आस-पास किराना स्टोर की खोज शुरू करने के लिए अपना ज़िप कोड सेट करें",
          "Select your city to start exploring grocery stores around you": "अपने आस-पास किराना स्टोर की खोज शुरू करने के लिए अपने शहर का चयन करें",
          "Select": "चुनना",
          "Welcome": "स्वागत",
          "Please login to your acount": "कृपया अपने खाते लॉग इन करें",
          "Password": "पासवर्ड",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Sign In": "साइन इन करें",
          "Don't have an account?": "खाता नहीं है?",
          " Sign Up": "साइन अप करें",
          "Phone Number": "फ़ोन नंबर",
          "Send OTP": "OTP भेजें",
          "Location": "स्थान",
          "House / Flat No": "मकान/फ्लैट नं",
          "Landmark": "सीमाचिह्न",
          "Pincode": "पिन कोड",
          "Save As": "के रूप रक्षित करें",
          "Home": "घर",
          "Work": "काम",
          "Other": "अन्य",
          "Add New Card": "नया कार्ड जोड़ें",
          "Card Holder Name": "कार्डधारक का नाम",
          "Card Number": "कार्ड नंबर",
          "CVC": "सीवीसी",
          "MM/YY": "महीना / साल",
          "Add Card": "कार्ड जोड़ें",
          "Offers": "ऑफर",
          "Rate Order": "दर आदेश",
          "Cancel Order": "आदेश रद्द",
          "More Details": "अधिक जानकारी",
          "Amount to Pay": "भुगतान की जाने वाली राशि",
          "Deliver to": "उसे देदो",
          "Basic Detail": "मूल विवरण",
          "Order ID": "आदेश ID",
          "Payment Method'": "भुगतान का तरीका",
          "COD": "सीओडी",
          "PAID": "भुगतान किया है",
          "Delivery On": "डिलीवरी चालू",
          "Order Tracking": "आदेश ट्रैकिंग",
          "Stores Information": "स्टोर की जानकारी",
          "Drivers Information": "ड्राइवरों की जानकारी",
          "Descriptions": "विवरण",
          "Heighlight": "प्रमुखता से दिखाना",
          "Disclaimer": "अस्वीकरण",
          "Maybe You Likes": "शायद आपको पसंद आए",
          "Refer & Earns": "देखें और कमाएं",
          "Invite Friends": "मित्रों को आमंत्रित करें",
          "Please register to your acount": "कृपया अपने खाते में पंजीकरण करें",
          "Referral Code (Optional)": "रेफरल कोड (वैकल्पिक)",
          "By continuing, you agree to our ": "जारी रखकर, आप हमारी सहमति देते हैं ",
          "Terms of Service": "सेवा की शर्तें",
          "Privacy Policy": "गोपनीयता नीति",
          " and ": " तथा ",
          "Sign Up": "साइन अप करें",
          "Already have an account?": "क्या आपके पास पहले से एक खाता मौजूद है?",
          " Sign In": " साइन इन करें",
          "Reset Password": "पासवर्ड रीसेट",
          "Please enter your credentials": "कृपया अपनी साख दर्ज करें",
          "New Password": "नया पासवर्ड",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Update Password": "पासवर्ड अपडेट करें",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Pay with Stripe": "स्ट्राइप के साथ भुगतान करें",
          "Expiry ": "समाप्ति ",
          "Payment ": "भुगतान ",
          "Account": "खाता",
          "Tracking Order": "ट्रैकिंग आदेश",
          "Store Information": "स्टोर की जानकारी",
          "Order Total": "कुल आर्डर",
          "Payment Method : ": "भुगतान का तरीका : ",
          "Driver Information": "चालक सूचना",
          "All Transactions": "सभी लेन - देन",
          "At Home": "घर पर",
          "Self Pickup": "स्व चयन",
          "Tomorrow - ": "कल का दिन - ",
          "Today - ": "आज - ",
          "Warning": "चेतावनी",
          "You already have item's in cart with different grocery store": "आपके पास पहले से ही विभिन्न किराना स्टोर वाले कार्ट में आइटम हैं",
          "Clear Cart": "कार्ट को खाली करें",
          "Confirm": "पुष्टि करें",
          "Are you sure to delete this?": "क्या आप निश्चित रूप से इसे हटाना चाहते हैं?",
          "Yes, Delete": "हां, हटाएं",
          "Minimum order amount must be ": "न्यूनतम आदेश राशि होनी चाहिए ",
          " or more": " या अधिक",
          "coupon codes": "कूपन कोड",
          "Use coupon code ": "कूपन कोड का प्रयोग करें",
          " - Valid until ": " - तब तक वैध",
          "Sorry minimum cart value must be ": "क्षमा करें, कार्ट का न्यूनतम मान होना चाहिए ",
          " or equal": " या बराबर",
          "Please Select Delivery Address": "कृपया वितरण पता चुनें",
          "Are you sure?": "क्या आपको यकीन है?",
          "Orders once placed cannot be cancelled and are non-refundable": "एक बार दिए गए आदेश रद्द नहीं किए जा सकते हैं और अप्रतिदेय हैं",
          "Yes, Place Order": "हां, ऑर्डर दें",
          "Please Select Payment Method": "कृपया भुगतान विधि चुनें",
          "Creating Order": "आदेश बनाना",
          "Your Order Created Successfully": "आपका आदेश सफलतापूर्वक बनाया गया",
          "You can view the order tracking info in the": "आप ऑर्डर ट्रैकिंग जानकारी देख सकते हैं",
          " Profile ": " प्रोफ़ाइल ",
          "section.": "खंड।",
          "Go to Home": "घर जाओ",
          "Go to Order": "ऑर्डर पर जाएं",
          "The product arrived too late": "उत्पाद बहुत देर से पहुंचा",
          "The product did not match the description": "उत्पाद विवरण से मेल नहीं खाता",
          "The purchase was fraudulent": "खरीद धोखाधड़ी थी",
          "The product was damaged or defective": "उत्पाद क्षतिग्रस्त या दोषपूर्ण था",
          "The merchant shipped the wrong item": "व्यापारी ने गलत वस्तु भेज दी",
          "Wrong Item Size or Wrong Product Shipped": "गलत आइटम का आकार या गलत उत्पाद भेज दिया गया",
          "Driver arrived too late": "ड्राइवर बहुत देर से पहुंचा",
          "Driver behavior": "चालक व्यवहार",
          "Store Vendors behavior": "स्टोर विक्रेताओं का व्यवहार",
          "Issue with Payment Amount": "भुगतान राशि के साथ समस्या",
          "Others": "अन्य",
          "Order": "आदेश",
          "Store": "स्टोर",
          "Driver": "चालक",
          "Product": "उत्पाद",
          "Choose Issue With": "के साथ समस्या चुनें",
          "Choose Store": "स्टोर चुनें",
          "Choose Driver": "ड्राइवर चुनें",
          "Choose Reason": "कारण चुनें",
          "Choose Product": "उत्पाद चुनें",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Complaints registered": "शिकायतें दर्ज",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल प्राप्त हुआ है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon": "हमें आपका अनुरोध प्राप्त हो गया है, हम जल्द ही आपके मुद्दे पर प्रतिक्रिया देंगे",
          "Alert!": "चेतावनी!",
          "Contact Information Sent": "संपर्क जानकारी भेजी गई",
          "Okay": "ठीक",
          "Profile Updated": "प्रोफाइल अद्यतन किया गया",
          "A-Z": "ए-जेड",
          "Z-A": "जेड-ए",
          "% Off": "% बंद",
          "Your account is suspended": "तुम्हारा खाता निलंबित है",
          "Something went wrong while signup": "साइन अप करते समय कुछ गलत हुआ",
          "Something went wrong": "कुछ गलत हो गया",
          "Congratulations your friend have received the ": "बधाई हो आपके मित्र को मिल गया है",
          " on wallet": "बटुए पर",
          "Congratulations you have received the ": "बधाई हो आपको मिली है",
          "Congratulations you & your friend have received the ": "बधाई हो आपको और आपके मित्र ने प्राप्त किया है",
          "Please add comments": "कृपया टिप्पणी जोड़ें",
          "Rating added": "रेटिंग जोड़ी गई",
          "Featching Location": "स्थान प्राप्त करना",
          "Location services are disabled.": "स्थान सेवाएं अक्षम हैं।",
          "Location permissions are denied": "स्थान अनुमतियां अस्वीकार कर दी गई हैं",
          "Location permissions are permanently denied, we cannot request permissions.": "स्थान अनुमतियों को स्थायी रूप से अस्वीकार कर दिया गया है, हम अनुमतियों का अनुरोध नहीं कर सकते।",
          "Please enter your zipcode": "कृपया अपना ज़िप कोड लिखें",
          "Phone Number is required": "फ़ोन नंबर आवश्यक है",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड को भेजा है",
          "Verify": "सत्यापित करना",
          "Add New Address": "नया पता जोड़ें",
          "Update Address": "पता अपडेट करें",
          "could not determine your location": "आपका स्थान निर्धारित नहीं कर सका",
          "Address saved": "पता सहेजा गया",
          "Address Updated": "पता अपडेट किया गया",
          "Card Information Saved": "कार्ड की जानकारी सहेजी गई",
          "Choose": "चुनना",
          "Chat": "बात करना",
          "Contact": "संपर्क करना",
          "Call": "बुलाना",
          "Billing Information": "बिलिंग जानकारी",
          "Order Item Total": "ऑर्डर आइटम कुल",
          "Order Delivery Charge": "ऑर्डर डिलीवरी चार्ज",
          "Split Order Tax": "स्प्लिट ऑर्डर टैक्स",
          "Split Order Discount": "स्प्लिट ऑर्डर डिस्काउंट",
          "Split Order Wallet Discount": "स्प्लिट ऑर्डर वॉलेट डिस्काउंट",
          "Rate Driver": "दर चालक",
          "to cancel this order?": "इस आदेश को रद्द करने के लिए?",
          "Yes, Cancel Order": "हाँ, आदेश रद्द करें",
          "Updating Order": "अद्यतन आदेश",
          "Status Updated": "स्थिति अपडेट",
          "Your friend": "आपके दोस्त",
          "has invited you to": "आपको आमंत्रित किया है",
          "Hey Buddy download": "अरे बडी डाउनलोड",
          "from app store and use my code": "ऐप स्टोर से और मेरे कोड का उपयोग करें",
          "while sign up we both will get": "साइन अप करते समय हम दोनों को मिलेगा",
          "wallet amount": "बटुआ राशि",
          "Share with buddies": "दोस्तों के साथ शेयर करें",
          "Copied to clipboard": "क्लिपबोर्ड पर नकल",
          "Use this code for verification": "सत्यापन के लिए इस कोड का प्रयोग करें",
          "Don't share this otp to anybody else": "इस ओटीपी को किसी और को शेयर न करें",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "Password Updated": "पासवर्ड अपडेट किया गया",
          "Please select card": "कृपया कार्ड चुनें",
          "Order Created": "आदेश बनाया गया",
          "Order cancelled by you": "आपके द्वारा रद्द किया गया आदेश",
          "Start Location": "प्रारंभ स्थान",
          "End Location": "अंतिम स्थान",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "About Us": "हमारे बारे में"
        },
        'es_DE': {
          "Profile": "Perfil",
          "Edit": "Editar",
          "Sign In / Sign Up": "Iniciar sesión, crear cuenta",
          "Orders": "Pedidos",
          "Favorites": "Favoritos",
          "Your Address": "Su dirección",
          "Wallet": "Cartera",
          "Refer & Earn": "Referir y ganar",
          "Change Password": "Cambia la contraseña",
          "Languages": "Idiomas",
          "Chats": "charlas",
          "Contact Us": "Contacta con nosotros",
          "Faq & Help": "Preguntas frecuentes y ayuda",
          "Privacy And Terms": "Privacidad y Términos",
          "About": "Sobre",
          "Logout": "Cerrar sesión",
          "Session expired!": "¡Sesión expirada!",
          "Please wait": "Espere por favor",
          "Address": "Dirección",
          "Add Address": "Añadir dirección",
          "Cart": "Carro",
          "Your cart is empty": "Tu carrito esta vacío",
          "Your Cart": "Tu carrito",
          "Order once placed cannot be cancelled and are non-refunable": "El pedido una vez realizado no se puede cancelar y no es reembolsable",
          " Items : ": "Elementos : ",
          "Checkout": "Verificar",
          " grams": " gramos",
          " kg": " kg",
          " ltr": " litros",
          " ml": " ml",
          " pcs": " piezas",
          "Choose variant": "Elegir variante",
          "Categories": "Categorías",
          "No Stores Found Near You!": "¡No se encontraron tiendas cerca de usted!",
          "Delivery Options": "Opciones de entrega",
          "Delivery Address": "Dirección de entrega",
          "Payments": "Pagos",
          "Note : Please visit all the stores listed on top": "Nota: visite todas las tiendas enumeradas en la parte superior",
          "Next": "Próximo",
          "Payment": "Pago",
          "Delivery from": "Entrega desde",
          "Stores": "Historias",
          "Delivery Time": "El tiempo de entrega",
          "Select Time": "Seleccionar hora",
          "Coupon Applied": "Cupón aplicado",
          "Apply Coupon code": "Aplicar código de cupón",
          "Remove": "Remover",
          "Balance": "Balance",
          "Available Balance ": "Saldo disponible ",
          "Item Total": "Total",
          "Taxes & Charges": "Impuestos y Cargos",
          "Discount": "Descuento",
          "Wallet Balance": "Saldo de la cartera",
          "Delivery Charges": "Los gastos de envío",
          "Grand Total": "Gran total",
          "Select Payment Gateway": "Seleccionar pasarela de pago",
          "Complaints": "Quejas",
          "Issue With": "Problema con",
          "Select Store": "Seleccionar tienda",
          "Select product": "Seleccionar producto",
          "Select Driver": "Seleccionar conductor",
          "Select reason": "Seleccione el motivo",
          "Title": "Título",
          "Brief of your issue": "Resumen de su problema",
          "Comments": "Comentarios",
          "Write something on issue": "Escribe algo sobre el tema",
          "Upload Image": "Cargar imagen",
          "Submit": "Enviar",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Message": "Mensaje",
          "Best Deals": "Mejores tratos",
          " Items": " Elementos",
          "Popularity": "Popularidad",
          "Price - Low to High": "Precio - Bajo a Alto",
          "Price L-H": "Precio L-H",
          "Price - Price L-H": "Precio - Precio L-H",
          "Price H-L": "Precio H-L",
          "A - Z": "A-Z",
          "Z - A": "Z - A",
          "% Off - High to Low": "% De descuento - Alto a bajo",
          "Filter ": "Filtrar ",
          "Add": "Agregar",
          "Edit Profile": "Editar perfil",
          "Choose From": "Escoge de",
          "Gallery": "Galería",
          "Camera": "Cámara",
          "Cancel": "Cancelar",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Email": "Correo electrónico",
          "Mobile No": "No móviles",
          "Save Profile": "Guardar perfil",
          "Connection Failed": "La conexión falló",
          "Could not connect to network,": "No se pudo conectar a la red,",
          "Please check and try again.": "Por favor revisa e intenta de nuevo.",
          "retry": "rever",
          "Your Favourite": "Tu favorito",
          "Verify your phone number": "verifica tu numero de telefono",
          "History": "Historia",
          "Opps, Please sign in or sign up first!": "¡Opps, inicia sesión o regístrate primero!",
          "ORDER # ": "ORDENAR #",
          "Search products": "Buscar Productos",
          "All Categories": "todas las categorias",
          "View All": "Ver todo",
          "Exclusive Offers": "Ofertas exclusivas",
          "Top Picked": "Los más elegidos",
          "Products For You": "Productos para ti",
          "Top Stores": "Las mejores tiendas",
          "View": "Vista",
          "Message...": "Mensaje...",
          "Fresh fruits and Vegetables": "frutas y verduras frescas",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "Las frutas y verduras frescas son una parte importante de una dieta saludable. Contienen vitaminas esenciales, minerales, fibra y otros nutrientes que son esenciales para una buena salud.",
          "Grocery to your door steps": "Comestibles a los pasos de su puerta",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "Poco a poco nos estamos volviendo más conscientes de cómo nuestras elecciones individuales pueden afectar nuestro planeta. Y la comida, cómo la consumimos y cómo la compramos, es una de las formas más importantes en que podemos marcar la diferencia.",
          "Best quality grocery": "Supermercado de la mejor calidad",
          "Best quality product with organic maintenance but with affordable price.": "Producto de la mejor calidad con mantenimiento orgánico pero con precio asequible.",
          "Fastest Delivery": "Entrega más rápida",
          "Free delivery service for highest cart value, without minimum payment.": "Servicio de entrega gratuito para el valor del carrito más alto, sin pago mínimo.",
          "Skip": "Saltar",
          "Previous": "Previo",
          "Get Started": "Empezar",
          "Enable Location": "Habilitar ubicación",
          "Set your location to start exploring grocery stores around you": "Establezca su ubicación para comenzar a explorar las tiendas de comestibles a su alrededor",
          "Use Current Location": "Usar ubicación actual",
          "Enter Zipcode": "Introduzca código postal",
          "Set your zipcode to start exploring grocery stores around you": "Configure su código postal para comenzar a explorar las tiendas de comestibles a su alrededor",
          "Select your city to start exploring grocery stores around you": "Seleccione su ciudad para comenzar a explorar las tiendas de comestibles a su alrededor",
          "Select": "Seleccione",
          "Welcome": "Bienvenidos",
          "Please login to your acount": "Por favor, ingrese a su cuenta",
          "Password": "Clave",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "Sign In": "Registrarse",
          "Don't have an account?": "¿No tienes una cuenta?",
          " Sign Up": "Inscribirse",
          "Phone Number": "Número de teléfono",
          "Send OTP": "Enviar OTP",
          "Location": "Ubicación",
          "House / Flat No": "Casa / Piso No",
          "Landmark": "Punto de referencia",
          "Pincode": "Código PIN",
          "Save As": "Guardar como",
          "Home": "Hogar",
          "Work": "Trabajar",
          "Other": "Otro",
          "Add New Card": "Agregar nueva tarjeta",
          "Card Holder Name": "Nombre del titular de la tarjeta",
          "Card Number": "Número de tarjeta",
          "CVC": "CVC",
          "MM/YY": "MM/AA",
          "Add Card": "Agregar tarjeta",
          "Offers": "Ofertas",
          "Rate Order": "Orden de tarifa",
          "Cancel Order": "Cancelar orden",
          "More Details": "Más detalles",
          "Amount to Pay": "Monto a pagar",
          "Deliver to": "Entregar a",
          "Basic Detail": "Detalle básico",
          "Order ID": "Solicitar ID",
          "Payment Method": "Método de pago",
          "COD": "BACALAO",
          "PAID": "PAGADO",
          "Delivery On": "Entrega en",
          "Order Tracking": "Rastreo de orden",
          "Stores Information": "Información de tiendas",
          "Drivers Information": "Información de los conductores",
          "Descriptions": "Descripciones",
          "Heighlight": "Destacar",
          "Disclaimer": "Descargo de responsabilidad",
          "Maybe You Likes": "Tal vez te guste",
          "Refer & Earns": "Recomendar y ganar",
          "Invite Friends": "Invitar a amigos",
          "Please register to your acount": "Por favor regístrese en su cuenta",
          "Referral Code (Optional)": "Código de Referencia (Opcional)",
          "By continuing, you agree to our ": "Al continuar, aceptas nuestros ",
          "Terms of Service": "Términos de servicio",
          "Privacy Policy": "Política de privacidad",
          " and ": " y ",
          "Sign Up": "Inscribirse",
          "Already have an account?": "¿Ya tienes una cuenta?",
          " Sign In": " Registrarse",
          "Reset Password": "Restablecer la contraseña",
          "Please enter your credentials": "Por favor ingrese sus credenciales",
          "New Password": "Nueva contraseña",
          "Confirm Password": "Confirmar contraseña",
          "Update Password": "Actualiza contraseña",
          "No Internet Connection": "Sin conexión a Internet",
          "Pay with Stripe": "Paga con Stripe",
          "Expiry ": "Expiración ",
          "Payment ": "Pago ",
          "Account": "Cuenta ",
          "Tracking Order": "Orden de seguimiento",
          "Store Information": "Almacenar información",
          "Order Total": "Total del pedido",
          "Payment Method : ": "Método de pago : ",
          "Driver Information": "Información del conductor",
          "All Transactions": "Todas las transacciones",
          "At Home": "En casa",
          "Self Pickup": "Recogerse",
          "Tomorrow - ": "Mañana - ",
          "Today - ": "Este Dia - ",
          "Warning": "Advertencia",
          "You already have item's in cart with different grocery store": "Ya tienes artículos en el carrito con otra tienda de comestibles",
          "Clear Cart": "Vaciar carrito",
          "Confirm": "Confirmar",
          "Are you sure to delete this?": "¿Estás seguro de eliminar esto?",
          "Yes, Delete": "Sí, Eliminar",
          "Minimum order amount must be ": "El monto mínimo del pedido debe ser",
          " or more": " o más",
          "coupon codes": "códigos de cupón",
          "Use coupon code ": "Usar código de cupón",
          " - Valid until ": " - Válido hasta ",
          "Sorry minimum cart value must be ": "Lo sentimos, el valor mínimo del carrito debe ser",
          " or equal": " o igual",
          "Please Select Delivery Address": "Seleccione la dirección de entrega",
          "Are you sure?": "Estas seguro",
          "Orders once placed cannot be cancelled and are non-refundable": "Los pedidos una vez realizados no se pueden cancelar y no son reembolsables",
          "Yes, Place Order": "Sí, realizar pedido",
          "Please Select Payment Method": "Seleccione el método de pago",
          "Creating Order": "Creando orden",
          "Your Order Created Successfully": "Tu pedido creado con éxito",
          "You can view the order tracking info in the": "Puede ver la información de seguimiento del pedido en el",
          " Profile ": " Perfil ",
          "section.": "sección.",
          "Go to Home": "Ir a casa",
          "Go to Order": "Ir a Pedido",
          "The product arrived too late": "El producto llego demasiado tarde",
          "The product did not match the description": "El producto no coincidía con la descripción.",
          "The purchase was fraudulent": "La compra fue fraudulenta",
          "The product was damaged or defective": "El producto estaba dañado o defectuoso",
          "The merchant shipped the wrong item": "El comerciante envió el artículo equivocado.",
          "Wrong Item Size or Wrong Product Shipped": "Tamaño de artículo incorrecto o producto enviado incorrecto",
          "Driver arrived too late": "El conductor llegó demasiado tarde",
          "Driver behavior": "Comportamiento del conductor",
          "Store Vendors behavior": "Comportamiento de los vendedores de la tienda",
          "Issue with Payment Amount": "Problema con el monto del pago",
          "Others": "Otros",
          "Order": "Ordenar",
          "Store": "Tienda",
          "Driver": "Conductor",
          "Product": "Producto",
          "Choose Issue With": "Elija Problema con",
          "Choose Store": "Elegir tienda",
          "Choose Driver": "Elegir conductor",
          "Choose Reason": "Elija la razón",
          "Choose Product": "Elija Producto",
          "All fields are required": "Todos los campos son obligatorios",
          "Complaints registered": "Quejas registradas",
          "Email is not valid": "El correo no es válido",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido correo nuevo",
          "New Contact Details": "Nuevos detalles de contacto",
          "We have received your request, we will respond on your issue soon": "Hemos recibido tu solicitud, pronto responderemos a tu problema.",
          "Alert!": "¡Alerta!",
          "Contact Information Sent": "Información de contacto enviada",
          "Okay": "De acuerdo",
          "Profile Updated": "Perfil actualizado",
          "A-Z": "A-Z",
          "Z-A": "Z-A",
          "% Off": "% Apagado",
          "Your account is suspended": "Tu cuenta está suspendida",
          "Something went wrong while signup": "Algo salió mal durante el registro",
          "Something went wrong": "Algo salió mal",
          "Congratulations your friend have received the ": "Enhorabuena, tu amigo ha recibido el",
          " on wallet": " en la billetera",
          "Congratulations you have received the ": "Felicidades has recibido el",
          "Congratulations you & your friend have received the ": "Felicitaciones, usted y su amigo han recibido el ",
          "Please add comments": "Por favor agregue comentarios",
          "Rating added": "Calificación añadida",
          "Featching Location": "Obtener ubicación",
          "Location services are disabled.": "Los servicios de ubicación están deshabilitados.",
          "Location permissions are denied": "Los permisos de ubicación están denegados",
          "Location permissions are permanently denied, we cannot request permissions.": "Los permisos de ubicación se niegan permanentemente, no podemos solicitar permisos.",
          "Please enter your zipcode": "Por favor ingrese su código postal",
          "Phone Number is required": "Se requiere número de teléfono",
          "Verification": "Verificación",
          "We have sent verification code on": "Hemos enviado el código de verificación el",
          "Verify": "Verificar",
          "Add New Address": "Agregar nueva dirección",
          "Update Address": "Actualizar dirección",
          "could not determine your location": "no se pudo determinar su ubicación",
          "Address saved": "Dirección guardada",
          "Address Updated": "Dirección actualizada",
          "Card Information Saved": "Información de la tarjeta guardada",
          "Choose": "Elegir",
          "Chat": "Charlar",
          "Contact": "Contacto",
          "Call": "Llamar",
          "Billing Information": "Datos de facturación",
          "Order Item Total": "Total del artículo del pedido",
          "Order Delivery Charge": "Cargo por envío del pedido",
          "Split Order Tax": "Impuesto de orden dividida",
          "Split Order Discount": "Descuento de pedido dividido",
          "Split Order Wallet Discount": "Descuento de billetera de pedido dividido",
          "Rate Driver": "Conductor de tarifa",
          "to cancel this order?": "cancelar este pedido?",
          "Yes, Cancel Order": "Sí, cancelar pedido",
          "Updating Order": "Orden de actualización",
          "Status Updated": "Estado actualizado",
          "Your friend": "Tu amigo",
          "has invited you to": "te ha invitado a",
          "Hey Buddy download": "Hola amigo descargar",
          "from app store and use my code": "de la tienda de aplicaciones y usa mi código",
          "while sign up we both will get": "mientras te registras ambos conseguiremos",
          "wallet amount": "monto de la billetera",
          "Share with buddies": "compartir con amigos",
          "Copied to clipboard": "Copiado al portapapeles",
          "Use this code for verification": "Utilice este código para la verificación",
          "Don't share this otp to anybody else": "No compartas este otp con nadie más.",
          "Password mismatch": "Contraseña no coincide",
          "Password Updated": "Contraseña actualiza",
          "Please select card": "Por favor, seleccione la tarjeta",
          "Order Created": "Pedido creado",
          "Order cancelled by you": "Pedido cancelado por usted",
          "Start Location": "Ubicación de inicio",
          "End Location": "Ubicación final",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "About Us": "Sobre nosotros"
        },
        'ar_AE': {
          "Profile": "الملف الشخصي",
          "Edit": "يحرر",
          "Sign In / Sign Up": "تسجيل الدخول / التسجيل",
          "Orders": "ترتيب",
          "Favorites": "المفضلة",
          "Your Address": "عنوانك",
          "Wallet": "محفظة",
          "Refer & Earn": "الإحالة وكسب",
          "Change Password": "غير كلمة السر",
          "Languages": "اللغات",
          "Chats": "الدردشات",
          "Contact Us": "اتصل بنا",
          "Faq & Help": "التعليمات و التعليمات",
          "Privacy And Terms": "الخصوصية والشروط",
          "About": "حول",
          "Logout": "تسجيل خروج",
          "Session expired!": "انتهت الجلسة!",
          "Please wait": "أرجو الإنتظار",
          "Address": "تبوك",
          "Add Address": "اضف عنوان",
          "Cart": "عربة التسوق",
          "Your cart is empty": "عربة التسوق فارغة",
          "Your Cart": "عربتك",
          "Order once placed cannot be cancelled and are non-refunable": "الطلب بمجرد تقديمه لا يمكن إلغاؤه وغير قابل للاسترداد",
          " Items : ": " العناصر : ",
          "Checkout": "الدفع",
          " grams": "جرامات ",
          " kg": "كلغ ",
          " ltr": "لتر ",
          " ml": "مل ",
          " pcs": "جهاز كمبيوتر شخصى ",
          "Choose variant": "اختر البديل",
          "Categories": "فئات",
          "No Stores Found Near You!": "لا توجد متاجر بالقرب منك!",
          "Delivery Options": "خيارات التوصيل",
          "Delivery Address": "عنوان التسليم",
          "Payments": "المدفوعات",
          "Note : Please visit all the stores listed on top": "ملاحظة: يرجى زيارة جميع المتاجر المدرجة في الأعلى",
          "Next": "التالي",
          "Payment": "دفع",
          "Delivery from": "التسليم من",
          "Stores": "المتاجر",
          "Delivery Time": "موعد التسليم",
          "Select Time": "حدد الوقت",
          "Coupon Applied": "تم تطبيق الكوبون",
          "Apply Coupon code": "تطبيق رمز القسيمة",
          "Remove": "إزالة",
          "Balance": "الرصيد",
          "Available Balance ": "الرصيد المتوفر ",
          "Item Total": "مجموع الاشياء ",
          "Taxes & Charges": "الضرائب والرسوم",
          "Discount": "تخفيض",
          "Wallet Balance": "رصيد المحفظة",
          "Delivery Charges": "رسوم التوصيل",
          "Grand Total": "المبلغ الإجمالي",
          "Select Payment Gateway": "حدد بوابة الدفع",
          "Complaints": "شكاوي",
          "Issue With": "القضية مع",
          "Select Store": "حدد المتجر",
          "Select product": "حدد المنتج",
          "Select Driver": "حدد السائق",
          "Select reason": "حدد السبب",
          "Title": "عنوان",
          "Brief of your issue": "موجز عن مشكلتك",
          "Comments": "تعليقات",
          "Write something on issue": "اكتب شيئا عن القضية",
          "Upload Image": "تحميل الصور",
          "Submit": "يُقدِّم",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الالكترونى",
          "Message": "رسالة",
          "Best Deals": "افضل العروض",
          " Items": "العناصر ",
          "Popularity": "شعبية",
          "Price - Low to High": "السعر من الارخص للاعلى",
          "Price L-H": "سعر L-H",
          "Price - Price L-H": "السعر - السعر L-H.",
          "Price H-L": "سعر H-L",
          "A - Z": "أ - ي",
          "Z - A": "ض - أ",
          "% Off - High to Low": "٪ خصم - من الأعلى إلى الأقل",
          "Filter ": "منقي ",
          "Add": "يضيف",
          "Edit Profile": "تعديل الملف الشخصي",
          "Choose From": "اختر من",
          "Gallery": "صالة عرض",
          "Camera": "آلة تصوير",
          "Cancel": "يلغي",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Email": "البريد الإلكتروني",
          "Mobile No": "رقم الموبايل",
          "Save Profile": "احفظ الملف",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network,": "تعذر الاتصال بالشبكة ،",
          "Please check and try again.": "يرجى مراجعة وحاول مرة أخرى.",
          "retry": "أعد المحاولة",
          "Your Favourite": "المفضل لديك",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "History": "تاريخ",
          "Opps, Please sign in or sign up first!": "عفوا ، الرجاء تسجيل الدخول أو التسجيل أولا!",
          "ORDER # ": "ترتيب #",
          "Search products": "البحث عن المنتجات",
          "All Categories": "جميع الفئات",
          "View All": "مشاهدة الكل",
          "Exclusive Offers": "عروض حصرية",
          "Top Picked": "الأعلى منتقاة",
          "Products For You": "منتجات لك",
          "Top Stores": "أفضل المتاجر",
          "View": "رأي",
          "Message...": "رسالة...",
          "Fresh fruits and Vegetables": "فواكه وخضروات طازجة",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "تعتبر الفواكه والخضروات الطازجة جزءًا مهمًا من النظام الغذائي الصحي. تحتوي على فيتامينات ومعادن وألياف أساسية وعناصر مغذية أخرى ضرورية لصحة جيدة",
          "Grocery to your door steps": "البقالة حتى عتبات بابك",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "أصبحنا ندرك ببطء أكثر كيف يمكن لخياراتنا الفردية أن تؤثر على كوكبنا. والطعام - كيف نستهلكه وكيف نتسوق له - هو أحد أهم الطرق التي يمكننا من خلالها إحداث فرق.",
          "Best quality grocery": "أفضل بقالة جودة",
          "Best quality product with organic maintenance but with affordable price.": "أفضل منتج عالي الجودة مع صيانة عضوية ولكن بسعر مناسب.",
          "Fastest Delivery": "أسرع توصيل",
          "Free delivery service for highest cart value, without minimum payment.": "خدمة توصيل مجانية لأعلى قيمة لسلة التسوق ، بدون حد أدنى للدفع.",
          "Skip": "يتخطى",
          "Previous": "سابق",
          "Get Started": "البدء",
          "Enable Location": "تمكن موقع",
          "Set your location to start exploring grocery stores around you": "حدد موقعك لبدء استكشاف متاجر البقالة من حولك",
          "Use Current Location": "استخدام الموقع الحالي",
          "Enter Zipcode": "أدخل الرمز البريدي",
          "Set your zipcode to start exploring grocery stores around you": "قم بتعيين الرمز البريدي الخاص بك لبدء استكشاف متاجر البقالة من حولك",
          "Select your city to start exploring grocery stores around you": "حدد مدينتك لبدء استكشاف متاجر البقالة من حولك",
          "Select": "يختار",
          "Welcome": "أهلا وسهلا",
          "Please login to your acount": "يرجى تسجيل الدخول إلى حسابك",
          "Password": "كلمة المرور",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Sign In": "تسجيل الدخول",
          "Don't have an account?": "ليس لديك حساب؟",
          " Sign Up": "اشتراك ",
          "Phone Number": "رقم الهاتف",
          "Send OTP": "أرسل OTP",
          "Location": "موقع",
          "House / Flat No": "منزل / شقة لا",
          "Landmark": "معلم معروف",
          "Pincode": "الرمز السري",
          "Save As": "حفظ باسم",
          "Home": "مسكن",
          "Work": "عمل",
          "Other": "آخر",
          "Add New Card": "إضافة بطاقة جديدة",
          "Card Holder Name": "إسم صاحب البطاقة",
          "Card Number": "رقم البطاقة",
          "CVC": "رمز التحقق من البطاقة (CVC)",
          "MM/YY": "شهر / سنة",
          "Add Card": "إضافة بطاقة",
          "Offers": "عروض",
          "Rate Order": "ترتيب معدل",
          "Cancel Order": "الغاء الطلب",
          "More Details": "المزيد من التفاصيل",
          "Amount to Pay": "مبلغ الدفع",
          "Deliver to": "يسلم إلى",
          "Basic Detail": "التفاصيل الأساسية",
          "Order ID": "رقم التعريف الخاص بالطلب",
          "Payment Method'": "طريقة الدفع او السداد",
          "COD": "سمك القد",
          "PAID": "دفع",
          "Delivery On": "التسليم في",
          "Order Tracking": "تتبع الطلب",
          "Stores Information": "معلومات المخازن",
          "Drivers Information": "معلومات السائقين",
          "Descriptions": "الأوصاف",
          "Heighlight": "تسليط الضوء",
          "Disclaimer": "تنصل",
          "Maybe You Likes": "ربما تحب",
          "Refer & Earns": "الإحالة والأرباح",
          "Invite Friends": "ادعو أصدقاء",
          "Please register to your acount": "الرجاء التسجيل في حسابك",
          "Referral Code (Optional)": "إحالة قانون (اختياري)",
          "By continuing, you agree to our ": "من خلال الاستمرار ، فإنك توافق على ",
          "Terms of Service": "شروط الخدمة",
          "Privacy Policy": "سياسة الخصوصية",
          " and ": " و ",
          "Sign Up": "اشتراك",
          "Already have an account?": "هل لديك حساب؟",
          " Sign In": "تسجيل الدخول ",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Please enter your credentials": "إعادة تعيين كلمة المرور",
          "New Password": "كلمة السر الجديدة",
          "Confirm Password": "تأكيد كلمة المرور",
          "Update Password": "تطوير كلمة السر",
          "No Internet Connection": "تطوير كلمة السر",
          "Pay with Stripe": "الدفع باستخدام Stripe",
          "Expiry ": "انقضاء ",
          "Payment ": "دفع ",
          "Account": "الحساب",
          "Tracking Order": "طلب التتبع",
          "Store Information": "معلومات المتجر",
          "Order Total": "الطلب الكلي",
          "Payment Method : ": "طريقة الدفع او السداد :",
          "Driver Information": "معلومات السائق",
          "All Transactions": "كل الحركات المالية",
          "At Home": "فى المنزل",
          "Self Pickup": "النفس التقاط",
          "Tomorrow - ": "الغد - ",
          "Today - ": "اليوم - ",
          "Warning": "تحذير",
          "You already have item's in cart with different grocery store": "لديك بالفعل عناصر في عربة التسوق مع متجر بقالة مختلف",
          "Clear Cart": "مسح السلة",
          "Confirm": "يتأكد",
          "Are you sure to delete this?": "هل أنت متأكد من حذف هذا؟",
          "Yes, Delete": "نعم ، احذف",
          "Minimum order amount must be ": "يجب أن يكون الحد الأدنى لمبلغ الطلب",
          " or more": "او اكثر ",
          "coupon codes": "رموز القسيمة",
          "Use coupon code ": "استخدم رمز القسيمة ",
          " - Valid until ": "- صالح حتى ",
          "Sorry minimum cart value must be ": "آسف يجب أن يكون الحد الأدنى لقيمة سلة التسوق ",
          " or equal": "أو يساوي",
          "Please Select Delivery Address": "يرجى تحديد عنوان التسليم",
          "Are you sure?": "هل أنت واثق؟",
          "Orders once placed cannot be cancelled and are non-refundable": "الطلبات بمجرد تقديمها لا يمكن إلغاؤها وغير قابلة للاسترداد",
          "Yes, Place Order": "نعم ، ضع الطلب",
          "Please Select Payment Method": "الرجاء تحديد طريقة الدفع",
          "Creating Order": "ترتيب إنشاء",
          "Your Order Created Successfully": "تم إنشاء طلبك بنجاح",
          "You can view the order tracking info in the": "يمكنك عرض معلومات تتبع الطلب في",
          " Profile ": "الملف الشخصي",
          "section.": "الجزء.",
          "Go to Home": "اذهب إلى الصفحة الرئيسية",
          "Go to Order": "اذهب إلى Order",
          "The product arrived too late": "وصل المنتج بعد فوات الأوان",
          "The product did not match the description": "المنتج لا يتطابق مع الوصف",
          "The purchase was fraudulent": "كان الشراء احتياليًا",
          "The product was damaged or defective": "المنتج تالف أو به عيب",
          "The merchant shipped the wrong item": "التاجر شحن العنصر الخطأ",
          "Wrong Item Size or Wrong Product Shipped": "حجم السلعة غير صحيح أو شحن منتج خاطئ",
          "Driver arrived too late": "وصل السائق بعد فوات الأوان",
          "Driver behavior": "سلوك السائق",
          "Store Vendors behavior": "سلوك بائعي المتجر",
          "Issue with Payment Amount": "مشكلة في مبلغ الدفع",
          "Others": "آحرون",
          "Order": "ترتيب",
          "Store": "متجر",
          "Driver": "سائق",
          "Product": "اختر المشكلة مع",
          "Choose Issue With": "",
          "Choose Store": "اختر المتجر",
          "Choose Driver": "اختر السائق",
          "Choose Reason": "اختر السبب",
          "Choose Product": "اختر المنتج",
          "All fields are required": "جميع الحقول مطلوبة",
          "Complaints registered": "تم تسجيل الشكاوى",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "New Mail Request Received": "تم استلام طلب بريد جديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل جهة اتصال جديدة",
          "We have received your request, we will respond on your issue soon": "لقد تلقينا طلبك ، وسنرد على مشكلتك قريبًا",
          "Alert!": "انذار!",
          "Contact Information Sent": "تم إرسال معلومات الاتصال",
          "Okay": "تمام",
          "Profile Updated": "تحديث الملف الشخصي",
          "A-Z": "من الألف إلى الياء",
          "Z-A": "Z-A",
          "% Off": "٪ عن",
          "Your account is suspended": "تم تعليق حسابك",
          "Something went wrong while signup": "حدث خطأ ما أثناء التسجيل",
          "Something went wrong": "هناك خطأ ما",
          "Congratulations your friend have received the ": "مبروك لقد تلقى صديقك",
          " on wallet": "على المحفظة",
          "Congratulations you have received the ": "تهانينا لقد تلقيت ",
          "Congratulations you & your friend have received the ": "تهانينا ، لقد تلقيت أنت وصديقك",
          "Please add comments": "الرجاء إضافة التعليقات",
          "Rating added": "تمت إضافة التقييم",
          "Featching Location": "إحضار الموقع",
          "Location services are disabled.": "خدمات الموقع معطلة.",
          "Location permissions are denied": "تم رفض أذونات الموقع",
          "Location permissions are permanently denied, we cannot request permissions.": "أذونات الموقع مرفوضة بشكل دائم ، ولا يمكننا طلب أذونات.",
          "Please enter your zipcode": "الرجاء إدخال الرمز البريدي الخاص بك",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Verify": "يؤكد",
          "Add New Address": "أضف عنوان جديد",
          "Update Address": "تحديث العنوان",
          "could not determine your location": "لا يمكن تحديد موقعك",
          "Address saved": "تم حفظ العنوان",
          "Address Updated": "تم تحديث العنوان",
          "Card Information Saved": "تم حفظ معلومات البطاقة",
          "Choose": "يختار",
          "Chat": "دردشة",
          "Contact": "اتصال",
          "Call": "مكالمة",
          "Billing Information": "معلومات الفواتير",
          "Order Item Total": "إجمالي عنصر الطلب",
          "Order Delivery Charge": "رسوم توصيل الطلب",
          "Split Order Tax": "تقسيم ضريبة الطلب",
          "Split Order Discount": "خصم الطلب المقسم",
          "Split Order Wallet Discount": "خصم محفظة الطلب المقسم",
          "Rate Driver": "معدل السائق",
          "to cancel this order?": "لإلغاء هذا الطلب؟",
          "Yes, Cancel Order": "نعم ، إلغاء الطلب",
          "Updating Order": "طلب التحديث",
          "Status Updated": "تم تحديث الحالة",
          "Your friend": "صديقك",
          "has invited you to": "دعاك إلى",
          "Hey Buddy download": "يا صديقي تنزيل",
          "from app store and use my code": "من متجر التطبيقات واستخدم الكود الخاص بي",
          "while sign up we both will get": "أثناء التسجيل سيحصل كل منا",
          "wallet amount": "مبلغ المحفظة",
          "Share with buddies": "شارك مع الاصدقاء",
          "Copied to clipboard": "نسخ إلى الحافظة",
          "Use this code for verification": "استخدم هذا الرمز للتحقق",
          "Don't share this otp to anybody else": "لا تشارك هذا otp مع أي شخص آخر",
          "Password mismatch": "كلمة المرور غير متطابقة",
          "Password Updated": "تم تحديث كلمة السر",
          "Please select card": "الرجاء تحديد البطاقة",
          "Order Created": "أجل خلق",
          "Order cancelled by you": "تم إلغاء الطلب بواسطتك",
          "Start Location": "بدء الموقع",
          "End Location": "موقع النهاية",
          "Frequently Asked Questions": "أسئلة مكررة",
          "About Us": "معلومات عنا"
        },
      };
}
